# Habilita AndroidX (obligatorio para tus dependencias)
android.useAndroidX=true
# Convierte librerías antiguas de soporte a AndroidX automáticamente
android.enableJetifier=true

# Aumenta la memoria para evitar errores de memoria en CI (opcional pero recomendado)
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
